version: "3.4"

services:
  cubesimulator:
    image: cubedraftsimuflaskcont.azurecr.io/eerondevcubesimulator
    build:
      context: .
      dockerfile: Simu_Dockerfile
    ports:
      - "80:80"
    networks:
      - thisnetwork
  
  nodeserver:
    image: cubedraftsimuflaskcont.azurecr.io/eerondevnodeserver
    build:
      context: .
      dockerfile: Server_Dockerfile_dev
    ports:
      - "3001:3001"
    networks:
      - thisnetwork

  flaskserver:
    image: cubedraftsimuflaskcont.azurecr.io/eerondevflaskserver
    build:
      context: .
      dockerfile: Flask_Dockerfile_dev
    ports:
      - "5002:5002"
    networks:
      - thisnetwork

networks:
  thisnetwork:
    driver: bridge